const {
  POSTGRES_URL,
  REDIS_URL,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI,
  ENCRYPTION_KEY,
  BASE_NOTIFICATION_URL,
  PORT,
  SERVICE_PORT,
  BASE_COLOR_URL,
  SECRET_KEY,
} = process.env;

module.exports = {
  POSTGRES_URL,
  REDIS_URL,
  POSTGRES_URL,
  REDIS_URL,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI,
  ENCRYPTION_KEY,
  BASE_NOTIFICATION_URL,
  PORT,
  SERVICE_PORT,
  BASE_COLOR_URL,
  SECRET_KEY,
}
